//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CPPLITE001_PROJEKT02_WXCRAFTER_BASE_CLASSES_H
#define _CPPLITE001_PROJEKT02_WXCRAFTER_BASE_CLASSES_H

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/stattext.h>
#include <wx/button.h>
#include <wx/textctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

#include "subinclude.h"
// clang-format on

class MainDialogBaseClass : public wxDialog
{
protected:
    wxStaticText* m_staticText37;
    wxButton* OpenBtn;
    wxButton* btn_save;
    wxTextCtrl* txtbox;
    wxButton* m_buttonOK;

protected:
    virtual void OnButton43ButtonClicked(wxCommandEvent& event)
    {
	event.Skip();
    }
    virtual void OnBtn_saveButtonClicked(wxCommandEvent& event)
    {
	event.Skip();
    }

public:
    wxStaticText* GetStaticText37()
    {
	return m_staticText37;
    }
    wxButton* GetOpenBtn()
    {
	return OpenBtn;
    }
    wxButton* GetBtn_save()
    {
	return btn_save;
    }
    wxTextCtrl* GetTxtbox()
    {
	return txtbox;
    }
    wxButton* GetButtonOK()
    {
	return m_buttonOK;
    }
    MainDialogBaseClass(wxWindow* parent,
        wxWindowID id = wxID_ANY,
        const wxString& title = _("Long's Text Editor"),
        const wxPoint& pos = wxDefaultPosition,
        const wxSize& size = wxSize(-1, -1),
        long style = wxDEFAULT_DIALOG_STYLE | wxFULL_REPAINT_ON_RESIZE | wxBORDER_STATIC);
    virtual ~MainDialogBaseClass();
};

#endif
